### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by DrDru** [mbalabanov/steganography#1]
Hey 

One of your blog post was shared Hacker News yesterday which is how I discovered your blog. I read you like comics and retro gaming.

I have a website that mixes both. I tell stories in Easy Japanese to help language learners in the form of a webcomic. It's illustrated with Pixel Art.
Also since you're a Front End dev you might appreciate the fact the illustrations are HTML and CSS not images (using box shadows).
 
It's here https://drdru.github.io/twc/twc_markus_ascent/chapter_1/02_meet_markus.html 
 
I don't really know what to expect from sharing it. I just thought you'd find it interesting.

Thanks for reading 

:-)

**Comment by mbalabanov** [comment]
Hey DrDu, 

thanks for sharing your work. I'm always interested in new things particularly from independent creators.
Looks awesome. I'll need to use Google Translate but I'll certainly take a close look.

Wish you all the best.

Cheers,
Marin

**Comment by mbalabanov** [comment]
Many thanks
